export const staffMembers = [
  {
    id: "1",
    staffId: "STF001",
    name: "Margaret Anderson",
    email: "margaret.anderson@school.edu",
    phone: "+1 (555) 234-5678",
    role: "Administrator",
    department: "Administration",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: "2",
    staffId: "STF002",
    name: "David Chen",
    email: "david.chen@school.edu",
    phone: "+1 (555) 345-6789",
    role: "Accountant",
    department: "Finance",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: "3",
    staffId: "STF003",
    name: "Patricia Williams",
    email: "patricia.williams@school.edu",
    phone: "+1 (555) 456-7890",
    role: "Librarian",
    department: "Library",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=45",
  },
  {
    id: "4",
    staffId: "STF004",
    name: "James Thompson",
    email: "james.thompson@school.edu",
    phone: "+1 (555) 567-8901",
    role: "Security Officer",
    department: "Security",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: "5",
    staffId: "STF005",
    name: "Maria Garcia",
    email: "maria.garcia@school.edu",
    phone: "+1 (555) 678-9012",
    role: "Nurse",
    department: "Health",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=44",
  },
  {
    id: "6",
    staffId: "STF006",
    name: "Robert Martinez",
    email: "robert.martinez@school.edu",
    phone: "+1 (555) 789-0123",
    role: "IT Support",
    department: "IT",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: "7",
    staffId: "STF007",
    name: "Linda Davis",
    email: "linda.davis@school.edu",
    phone: "+1 (555) 890-1234",
    role: "Receptionist",
    department: "Front Desk",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=48",
  },
  {
    id: "8",
    staffId: "STF008",
    name: "Charles Wilson",
    email: "charles.wilson@school.edu",
    phone: "+1 (555) 901-2345",
    role: "Driver",
    department: "Transport",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: "9",
    staffId: "STF009",
    name: "Barbara Moore",
    email: "barbara.moore@school.edu",
    phone: "+1 (555) 012-3456",
    role: "Counselor",
    department: "Counseling",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=49",
  },
  {
    id: "10",
    staffId: "STF010",
    name: "Joseph Taylor",
    email: "joseph.taylor@school.edu",
    phone: "+1 (555) 123-4567",
    role: "Janitor",
    department: "Maintenance",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=11",
  },
  {
    id: "11",
    staffId: "STF011",
    name: "Susan Jackson",
    email: "susan.jackson@school.edu",
    phone: "+1 (555) 234-6789",
    role: "HR Manager",
    department: "Human Resources",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=43",
  },
  {
    id: "12",
    staffId: "STF012",
    name: "Daniel White",
    email: "daniel.white@school.edu",
    phone: "+1 (555) 345-7890",
    role: "Procurement Officer",
    department: "Procurement",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=17",
  },
  {
    id: "13",
    staffId: "STF013",
    name: "Karen Harris",
    email: "karen.harris@school.edu",
    phone: "+1 (555) 456-8901",
    role: "Security Officer",
    department: "Security",
    status: "Active",
    type: "Part-time",
    image: "https://i.pravatar.cc/150?img=46",
  },
  {
    id: "14",
    staffId: "STF014",
    name: "Mark Clark",
    email: "mark.clark@school.edu",
    phone: "+1 (555) 567-9012",
    role: "Janitor",
    department: "Maintenance",
    status: "On Leave",
    type: "Contract",
    image: "https://i.pravatar.cc/150?img=16",
  },
];
