export interface StaffMember {
  id: string;
  staffId: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  department: string;
  status: string;
  type: string;
  image: string;
  dateOfBirth: string;
  gender: string;
  address: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
  joinDate: string;
  salary: string;
  attendanceRate: number;
  tasksCompleted: number;
  punctualityScore: number;
  feedbackRating: number;
}

export const staffMembers: StaffMember[] = [
  {
    id: "1",
    staffId: "STF001",
    name: "Margaret Anderson",
    email: "margaret.anderson@school.edu",
    phone: "+1 (555) 234-5678",
    role: "Administrator",
    department: "Administration",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=47",
    dateOfBirth: "March 15, 1978",
    gender: "Female",
    address: "456 Oak Avenue, Springfield, IL 62701",
    emergencyContactName: "Robert Anderson",
    emergencyContactPhone: "+1 (555) 234-5679",
    joinDate: "August 1, 2015",
    salary: "₦65,000",
    attendanceRate: 94,
    tasksCompleted: 87,
    punctualityScore: 96,
    feedbackRating: 4.5,
  },
  {
    id: "2",
    staffId: "STF002",
    name: "David Chen",
    email: "david.chen@school.edu",
    phone: "+1 (555) 345-6789",
    role: "Accountant",
    department: "Finance",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=12",
    dateOfBirth: "June 22, 1985",
    gender: "Male",
    address: "123 Maple Street, Springfield, IL 62702",
    emergencyContactName: "Lisa Chen",
    emergencyContactPhone: "+1 (555) 345-6780",
    joinDate: "March 15, 2018",
    salary: "₦55,000",
    attendanceRate: 92,
    tasksCompleted: 91,
    punctualityScore: 89,
    feedbackRating: 4.2,
  },
  {
    id: "3",
    staffId: "STF003",
    name: "Patricia Williams",
    email: "patricia.williams@school.edu",
    phone: "+1 (555) 456-7890",
    role: "Librarian",
    department: "Library",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=45",
    dateOfBirth: "January 8, 1980",
    gender: "Female",
    address: "789 Elm Boulevard, Springfield, IL 62703",
    emergencyContactName: "Thomas Williams",
    emergencyContactPhone: "+1 (555) 456-7891",
    joinDate: "September 1, 2016",
    salary: "₦48,000",
    attendanceRate: 97,
    tasksCompleted: 93,
    punctualityScore: 98,
    feedbackRating: 4.8,
  },
  {
    id: "4",
    staffId: "STF004",
    name: "James Thompson",
    email: "james.thompson@school.edu",
    phone: "+1 (555) 567-8901",
    role: "Security Officer",
    department: "Security",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=15",
    dateOfBirth: "November 30, 1975",
    gender: "Male",
    address: "321 Pine Road, Springfield, IL 62704",
    emergencyContactName: "Sarah Thompson",
    emergencyContactPhone: "+1 (555) 567-8902",
    joinDate: "January 10, 2014",
    salary: "₦42,000",
    attendanceRate: 98,
    tasksCompleted: 85,
    punctualityScore: 99,
    feedbackRating: 4.6,
  },
  {
    id: "5",
    staffId: "STF005",
    name: "Maria Garcia",
    email: "maria.garcia@school.edu",
    phone: "+1 (555) 678-9012",
    role: "Nurse",
    department: "Health",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=44",
    dateOfBirth: "April 19, 1982",
    gender: "Female",
    address: "654 Birch Lane, Springfield, IL 62705",
    emergencyContactName: "Carlos Garcia",
    emergencyContactPhone: "+1 (555) 678-9013",
    joinDate: "May 20, 2017",
    salary: "₦52,000",
    attendanceRate: 96,
    tasksCompleted: 90,
    punctualityScore: 94,
    feedbackRating: 4.7,
  },
  {
    id: "6",
    staffId: "STF006",
    name: "Robert Martinez",
    email: "robert.martinez@school.edu",
    phone: "+1 (555) 789-0123",
    role: "IT Support",
    department: "IT",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=13",
    dateOfBirth: "August 5, 1990",
    gender: "Male",
    address: "987 Cedar Court, Springfield, IL 62706",
    emergencyContactName: "Ana Martinez",
    emergencyContactPhone: "+1 (555) 789-0124",
    joinDate: "October 1, 2020",
    salary: "₦58,000",
    attendanceRate: 88,
    tasksCompleted: 95,
    punctualityScore: 85,
    feedbackRating: 4.3,
  },
  {
    id: "7",
    staffId: "STF007",
    name: "Linda Davis",
    email: "linda.davis@school.edu",
    phone: "+1 (555) 890-1234",
    role: "Receptionist",
    department: "Front Desk",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=48",
    dateOfBirth: "December 12, 1988",
    gender: "Female",
    address: "246 Walnut Drive, Springfield, IL 62707",
    emergencyContactName: "Mark Davis",
    emergencyContactPhone: "+1 (555) 890-1235",
    joinDate: "February 14, 2019",
    salary: "₦40,000",
    attendanceRate: 91,
    tasksCompleted: 82,
    punctualityScore: 93,
    feedbackRating: 4.1,
  },
  {
    id: "8",
    staffId: "STF008",
    name: "Charles Wilson",
    email: "charles.wilson@school.edu",
    phone: "+1 (555) 901-2345",
    role: "Driver",
    department: "Transport",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=14",
    dateOfBirth: "July 25, 1979",
    gender: "Male",
    address: "135 Spruce Way, Springfield, IL 62708",
    emergencyContactName: "Dorothy Wilson",
    emergencyContactPhone: "+1 (555) 901-2346",
    joinDate: "June 5, 2013",
    salary: "₦38,000",
    attendanceRate: 93,
    tasksCompleted: 78,
    punctualityScore: 91,
    feedbackRating: 4.0,
  },
  {
    id: "9",
    staffId: "STF009",
    name: "Barbara Moore",
    email: "barbara.moore@school.edu",
    phone: "+1 (555) 012-3456",
    role: "Counselor",
    department: "Counseling",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=49",
    dateOfBirth: "September 3, 1984",
    gender: "Female",
    address: "864 Poplar Street, Springfield, IL 62709",
    emergencyContactName: "Richard Moore",
    emergencyContactPhone: "+1 (555) 012-3457",
    joinDate: "August 20, 2016",
    salary: "₦50,000",
    attendanceRate: 95,
    tasksCompleted: 89,
    punctualityScore: 97,
    feedbackRating: 4.9,
  },
  {
    id: "10",
    staffId: "STF010",
    name: "Joseph Taylor",
    email: "joseph.taylor@school.edu",
    phone: "+1 (555) 123-4567",
    role: "Janitor",
    department: "Maintenance",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=11",
    dateOfBirth: "February 28, 1977",
    gender: "Male",
    address: "579 Ash Avenue, Springfield, IL 62710",
    emergencyContactName: "Helen Taylor",
    emergencyContactPhone: "+1 (555) 123-4568",
    joinDate: "April 1, 2012",
    salary: "₦35,000",
    attendanceRate: 90,
    tasksCompleted: 80,
    punctualityScore: 88,
    feedbackRating: 3.8,
  },
  {
    id: "11",
    staffId: "STF011",
    name: "Susan Jackson",
    email: "susan.jackson@school.edu",
    phone: "+1 (555) 234-6789",
    role: "HR Manager",
    department: "Human Resources",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=43",
    dateOfBirth: "October 17, 1981",
    gender: "Female",
    address: "312 Chestnut Place, Springfield, IL 62711",
    emergencyContactName: "William Jackson",
    emergencyContactPhone: "+1 (555) 234-6790",
    joinDate: "November 15, 2017",
    salary: "₦62,000",
    attendanceRate: 96,
    tasksCompleted: 92,
    punctualityScore: 95,
    feedbackRating: 4.6,
  },
  {
    id: "12",
    staffId: "STF012",
    name: "Daniel White",
    email: "daniel.white@school.edu",
    phone: "+1 (555) 345-7890",
    role: "Procurement Officer",
    department: "Procurement",
    status: "Active",
    type: "Full-time",
    image: "https://i.pravatar.cc/150?img=17",
    dateOfBirth: "May 9, 1987",
    gender: "Male",
    address: "741 Hickory Lane, Springfield, IL 62712",
    emergencyContactName: "Jennifer White",
    emergencyContactPhone: "+1 (555) 345-7891",
    joinDate: "July 1, 2019",
    salary: "₦53,000",
    attendanceRate: 89,
    tasksCompleted: 86,
    punctualityScore: 90,
    feedbackRating: 4.1,
  },
  {
    id: "13",
    staffId: "STF013",
    name: "Karen Harris",
    email: "karen.harris@school.edu",
    phone: "+1 (555) 456-8901",
    role: "Security Officer",
    department: "Security",
    status: "Active",
    type: "Part-time",
    image: "https://i.pravatar.cc/150?img=46",
    dateOfBirth: "March 21, 1992",
    gender: "Female",
    address: "258 Willow Road, Springfield, IL 62713",
    emergencyContactName: "Michael Harris",
    emergencyContactPhone: "+1 (555) 456-8902",
    joinDate: "January 5, 2022",
    salary: "₦28,000",
    attendanceRate: 85,
    tasksCompleted: 79,
    punctualityScore: 87,
    feedbackRating: 3.9,
  },
  {
    id: "14",
    staffId: "STF014",
    name: "Mark Clark",
    email: "mark.clark@school.edu",
    phone: "+1 (555) 567-9012",
    role: "Janitor",
    department: "Maintenance",
    status: "On Leave",
    type: "Contract",
    image: "https://i.pravatar.cc/150?img=16",
    dateOfBirth: "August 14, 1995",
    gender: "Male",
    address: "963 Dogwood Circle, Springfield, IL 62714",
    emergencyContactName: "Nancy Clark",
    emergencyContactPhone: "+1 (555) 567-9013",
    joinDate: "September 10, 2023",
    salary: "₦30,000",
    attendanceRate: 72,
    tasksCompleted: 65,
    punctualityScore: 78,
    feedbackRating: 3.5,
  },
];
