// Mock Data
export const students = [
  {
    id: "1",
    admissionNo: "SMS/2026/001",
    name: "Emily Rodriguez",
    gender: "Female",
    class: "JSS 3",
    arm: "Gold",
    guardian: "Maria Rodriguez",
    contact: "+1 (555) 789-0123",
    status: "Active",
    feesOwed: 500,
    image: "https://readdy.ai/api/search-image?query=young%20female%20high%20school%20student%20portrait%20clean%20white%20background%20school%20uniform%20bright%20smile%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-emily-001&orientation=squarish",
    details: {
      dob: "5/15/2008",
      admissionDate: "9/1/2023",
      previousSchool: "Lincoln Elementary School",
      address: "456 Oak Avenue, Springfield",
      guardianEmail: "maria.rodriguez@email.com",
    },
    medical: {
      bloodGroup: "O+",
      genotype: "AA",
      allergies: "None",
      conditions: "None",
    },
    performance: {
      gpa: "3.8",
      attendanceRate: "96.5%",
      totalFees: 5000,
      amountPaid: 4500,
    },
    academicHistory: [
      { term: "First Term 2023", average: "85.5%", position: 3, outOf: 45 },
      { term: "Second Term 2023", average: "87.2%", position: 2, outOf: 45 },
      { term: "Third Term 2023", average: "88.8%", position: 1, outOf: 45 },
    ],
    attendanceSummary: { present: 20, absent: 1, late: 0, excused: 1 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: true },
    auditLogs: [
      { action: "Updated contact number", date: "2/10/2024, 10:15:00 AM", prev: "+1 (555) 111-2222", new: "+1 (555) 789-0123", by: "Dr. Sarah Johnson" }
    ]
  },
  {
    id: "2",
    admissionNo: "SMS/2026/002",
    name: "James Thompson",
    gender: "Male",
    class: "SSS 1",
    arm: "Blue",
    guardian: "Robert Thompson",
    contact: "+1 (555) 901-2345",
    status: "Active",
    feesOwed: 0,
    image: "https://readdy.ai/api/search-image?query=young%20male%20high%20school%20student%20portrait%20clean%20white%20background%20school%20uniform%20confident%20smile%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-james-002&orientation=squarish",
    details: {
      dob: "8/22/2007",
      admissionDate: "9/1/2022",
      previousSchool: "Washington Middle School",
      address: "789 Maple Street, Springfield",
      guardianEmail: "robert.thompson@email.com",
    },
    medical: {
      bloodGroup: "A+",
      genotype: "AS",
      allergies: "Peanuts",
      conditions: "Asthma",
    },
    performance: {
      gpa: "3.6",
      attendanceRate: "94.2%",
      totalFees: 5000,
      amountPaid: 5000,
    },
    academicHistory: [
      { term: "First Term 2023", average: "78.5%", position: 12, outOf: 40 },
      { term: "Second Term 2023", average: "81.0%", position: 8, outOf: 40 },
      { term: "Third Term 2023", average: "82.5%", position: 6, outOf: 40 },
    ],
    attendanceSummary: { present: 18, absent: 2, late: 1, excused: 1 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: true },
    auditLogs: [
      { action: "Updated date of birth", date: "1/18/2024, 3:30:00 PM", prev: "2008-05-14", new: "2008-05-15", by: "Dr. Sarah Johnson" }
    ]
  },
  {
    id: "3",
    admissionNo: "SMS/2026/003",
    name: "Sophia Chen",
    gender: "Female",
    class: "SSS 3",
    arm: "Gold",
    guardian: "Linda Chen",
    contact: "+1 (555) 123-4567",
    status: "Active",
    feesOwed: 0,
    image: "https://readdy.ai/api/search-image?query=young%20female%20asian%20high%20school%20student%20portrait%20clean%20white%20background%20school%20uniform%20warm%20smile%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-sophia-003&orientation=squarish",
    details: {
      dob: "3/10/2006",
      admissionDate: "9/1/2021",
      previousSchool: "International Academy",
      address: "101 Pine Road, Springfield",
      guardianEmail: "linda.chen@email.com",
    },
    medical: {
      bloodGroup: "B+",
      genotype: "AA",
      allergies: "None",
      conditions: "None",
    },
    performance: {
      gpa: "4.0",
      attendanceRate: "99.0%",
      totalFees: 5000,
      amountPaid: 5000,
    },
    academicHistory: [
      { term: "First Term 2023", average: "95.5%", position: 1, outOf: 35 },
      { term: "Second Term 2023", average: "96.2%", position: 1, outOf: 35 },
      { term: "Third Term 2023", average: "97.0%", position: 1, outOf: 35 },
    ],
    attendanceSummary: { present: 22, absent: 0, late: 0, excused: 0 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: true },
    auditLogs: []
  },
  {
    id: "4",
    admissionNo: "SMS/2026/004",
    name: "Michael Okonkwo",
    gender: "Male",
    class: "JSS 2",
    arm: "Blue",
    guardian: "Chioma Okonkwo",
    contact: "+1 (555) 234-5678",
    status: "Active",
    feesOwed: 2000,
    image: "https://readdy.ai/api/search-image?query=young%20male%20african%20student%20portrait%20clean%20white%20background%20school%20uniform%20friendly%20smile%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-michael-004&orientation=squarish",
    details: {
      dob: "11/05/2009",
      admissionDate: "9/1/2024",
      previousSchool: "St. Jude Primary",
      address: "222 Cedar Lane, Springfield",
      guardianEmail: "chioma.o@email.com",
    },
    medical: {
      bloodGroup: "O-",
      genotype: "AS",
      allergies: "Dust",
      conditions: "None",
    },
    performance: {
      gpa: "3.2",
      attendanceRate: "88.5%",
      totalFees: 5000,
      amountPaid: 3000,
    },
    academicHistory: [
      { term: "First Term 2023", average: "70.5%", position: 20, outOf: 42 },
      { term: "Second Term 2023", average: "72.2%", position: 18, outOf: 42 },
      { term: "Third Term 2023", average: "75.0%", position: 15, outOf: 42 },
    ],
    attendanceSummary: { present: 16, absent: 3, late: 2, excused: 1 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: false },
    auditLogs: []
  },
  {
    id: "5",
    admissionNo: "SMS/2026/005",
    name: "Aisha Mohammed",
    gender: "Female",
    class: "SSS 2",
    arm: "Gold",
    guardian: "Fatima Mohammed",
    contact: "+1 (555) 345-6789",
    status: "Active",
    feesOwed: 0,
    image: "https://readdy.ai/api/search-image?query=young%20female%20muslim%20student%20portrait%20with%20hijab%20clean%20white%20background%20school%20uniform%20warm%20smile%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-aisha-005&orientation=squarish",
    details: {
      dob: "2/14/2007",
      admissionDate: "9/1/2022",
      previousSchool: "Crescent High",
      address: "333 Birch Street, Springfield",
      guardianEmail: "fatima.m@email.com",
    },
    medical: {
      bloodGroup: "AB+",
      genotype: "AA",
      allergies: "None",
      conditions: "None",
    },
    performance: {
      gpa: "3.9",
      attendanceRate: "98.0%",
      totalFees: 5000,
      amountPaid: 5000,
    },
    academicHistory: [
      { term: "First Term 2023", average: "90.0%", position: 4, outOf: 38 },
      { term: "Second Term 2023", average: "91.5%", position: 3, outOf: 38 },
      { term: "Third Term 2023", average: "92.0%", position: 2, outOf: 38 },
    ],
    attendanceSummary: { present: 21, absent: 0, late: 1, excused: 0 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: true },
    auditLogs: []
  },
  {
    id: "6",
    admissionNo: "SMS/2026/006",
    name: "David Kim",
    gender: "Male",
    class: "JSS 3",
    arm: "Blue",
    guardian: "Sarah Kim",
    contact: "+1 (555) 456-7890",
    status: "Active",
    feesOwed: 200,
    image: "https://readdy.ai/api/search-image?query=young%20male%20asian%20student%20portrait%20clean%20white%20background%20school%20uniform%20confident%20expression%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-david-006&orientation=squarish",
    details: {
      dob: "7/30/2008",
      admissionDate: "9/1/2023",
      previousSchool: "Springfield Elementary",
      address: "444 Elm Drive, Springfield",
      guardianEmail: "sarah.kim@email.com",
    },
    medical: {
      bloodGroup: "B-",
      genotype: "AA",
      allergies: "Seafood",
      conditions: "None",
    },
    performance: {
      gpa: "3.5",
      attendanceRate: "92.0%",
      totalFees: 5000,
      amountPaid: 4800,
    },
    academicHistory: [
      { term: "First Term 2023", average: "75.0%", position: 15, outOf: 40 },
      { term: "Second Term 2023", average: "78.0%", position: 10, outOf: 40 },
      { term: "Third Term 2023", average: "80.0%", position: 8, outOf: 40 },
    ],
    attendanceSummary: { present: 19, absent: 1, late: 2, excused: 0 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: true },
    auditLogs: []
  },
  {
    id: "7",
    admissionNo: "SMS/2026/007",
    name: "Isabella Garcia",
    gender: "Female",
    class: "SSS 1",
    arm: "Gold",
    guardian: "Carlos Garcia",
    contact: "+1 (555) 567-8901",
    status: "Active",
    feesOwed: 0,
    image: "https://readdy.ai/api/search-image?query=young%20female%20hispanic%20student%20portrait%20clean%20white%20background%20school%20uniform%20bright%20smile%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-isabella-007&orientation=squarish",
    details: {
      dob: "12/12/2007",
      admissionDate: "9/1/2022",
      previousSchool: "Liberty Middle School",
      address: "555 Walnut Way, Springfield",
      guardianEmail: "carlos.g@email.com",
    },
    medical: {
      bloodGroup: "A-",
      genotype: "AS",
      allergies: "None",
      conditions: "None",
    },
    performance: {
      gpa: "3.7",
      attendanceRate: "95.5%",
      totalFees: 5000,
      amountPaid: 5000,
    },
    academicHistory: [
      { term: "First Term 2023", average: "82.0%", position: 9, outOf: 35 },
      { term: "Second Term 2023", average: "84.5%", position: 7, outOf: 35 },
      { term: "Third Term 2023", average: "86.0%", position: 5, outOf: 35 },
    ],
    attendanceSummary: { present: 20, absent: 1, late: 1, excused: 0 },
    disciplinary: [],
    documents: { birthCertificate: true, transcript: true, medicalReport: true },
    auditLogs: []
  },
  {
    id: "8",
    admissionNo: "SMS/2026/008",
    name: "Ethan Williams",
    gender: "Male",
    class: "JSS 2",
    arm: "Gold",
    guardian: "Jennifer Williams",
    contact: "+1 (555) 678-9012",
    status: "Suspended",
    feesOwed: 2500,
    image: "https://readdy.ai/api/search-image?query=young%20male%20student%20portrait%20clean%20white%20background%20school%20uniform%20serious%20expression%20natural%20lighting%20professional%20student%20photo&width=200&height=200&seq=student-ethan-008&orientation=squarish",
    details: {
      dob: "4/08/2009",
      admissionDate: "9/1/2024",
      previousSchool: "Springfield Elementary",
      address: "666 Ash Court, Springfield",
      guardianEmail: "jennifer.w@email.com",
    },
    medical: {
      bloodGroup: "O+",
      genotype: "AA",
      allergies: "None",
      conditions: "None",
    },
    performance: {
      gpa: "2.4",
      attendanceRate: "75.0%",
      totalFees: 5000,
      amountPaid: 2500,
    },
    academicHistory: [
      { term: "First Term 2023", average: "55.0%", position: 38, outOf: 40 },
      { term: "Second Term 2023", average: "58.5%", position: 35, outOf: 40 },
      { term: "Third Term 2023", average: "60.0%", position: 30, outOf: 40 },
    ],
    attendanceSummary: { present: 12, absent: 6, late: 4, excused: 0 },
    disciplinary: [
      {
        incident: "Fighting in the cafeteria",
        date: "1/15/2024",
        actionTaken: "3-day suspension",
        description: "Student involved in physical altercation with peer",
        reportedBy: "Mr. David Kumar"
      },
      {
        incident: "Repeated tardiness",
        date: "11/20/2023",
        actionTaken: "Warning letter to parent",
        description: "Late to class 5 times in one week",
        reportedBy: "Ms. Jennifer Lopez"
      }
    ],
    documents: { birthCertificate: true, transcript: false, medicalReport: true },
    auditLogs: [
      { action: "Updated status", date: "1/15/2024, 5:45:00 PM", prev: "Active", new: "Suspended", by: "Dr. Sarah Johnson" }
    ]
  },
];